
on:
  workflow_dispatch:
# act --secret-file .github/workflows/.secrets -W ./.github/workflows/local_test_custom_action.yaml workflow_dispatch
jobs:
  local_test:
    runs-on: ubuntu-latest
    name: Sync github secrets into AWS environment
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.INTERNAL_AWS_REGION }}
      AWS_TGT_SECRETS_ARN:  ${{ secrets.INTERNAL_AWS_TGT_SECRETS_ARN }}
      INCLUDE_FILTER: "STAGING_" # OPTIONAL
      EXCLUDE_FILTER: "INTERNAL_" 
      REMOVE_PATTERN: "STAGING_" # OPTIONAL
      SECRETS_CONFIG_FILE: secret_config.json
      # DEBUG Local test
      SCRIPT_DIR: "./github-action-aws-secrets-sync/"      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "github-action-aws-secrets-sync"
      - run: echo "${{ toJson(secrets) }}" > ${{ env.SECRETS_CONFIG_FILE }}
      - name: Sync github secrets into AWS Secrets Manager
        uses: ./github-action-aws-secrets-sync # Uses an action in the root directory
        id: secretsyncer
