name: Sync Github Secrets into AWS Secrets Manager

on:
  workflow_dispatch:

jobs:
  sync-staging-secrets:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      AWS_DEFAULT_REGION: ${{ secrets.INTERNAL_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_AWS_SECRET_ACCESS_KEY }}
      # AWS_SESSION_TOKEN:  ${{ secrets.INTERNAL_AWS_SESSION_TOKEN }}
      AWS_TGT_SECRETS_ARN:  ${{ secrets.INTERNAL_AWS_TGT_SECRETS_ARN }}
      SECRETS_CONFIG_FILE: secret_config.json
    steps:
      - uses: actions/checkout@v2

      - name: Create secrets json file
        run: echo "${{ toJson(secrets) }}" > ${{ env.SECRETS_CONFIG_FILE }}

      - name: Sync github secrets into AWS Secrets Manager for the Staging Environment
        uses: juliandgon/github-action-aws-secrets-sync@stable
        id: secretsyncer

      - name: Delete secrets file
        run: rm ${{ env.SECRETS_CONFIG_FILE }}
  sync-live-secrets:
    runs-on: ubuntu-latest
    environment: Live
    env:
      AWS_DEFAULT_REGION: ${{ secrets.INTERNAL_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_AWS_SECRET_ACCESS_KEY }}
      # AWS_SESSION_TOKEN:  ${{ secrets.INTERNAL_AWS_SESSION_TOKEN }}
      AWS_TGT_SECRETS_ARN:  ${{ secrets.INTERNAL_AWS_TGT_SECRETS_ARN }}
      SECRETS_CONFIG_FILE: secret_config.json
    steps:
      - uses: actions/checkout@v2

      - name: Create secrets json file
        run: echo "${{ toJson(secrets) }}" > ${{ env.SECRETS_CONFIG_FILE }}

      - name: Sync github secrets into AWS Secrets Manager for the Live Environment
        uses: juliandgon/github-action-aws-secrets-sync@stable
        id: secretsyncer

      - name: Delete secrets file
        run: rm ${{ env.SECRETS_CONFIG_FILE }}
